### ISSUE TITLE
Getting Null pointer exception running the featurefile

### ISSUE THREAD

**Issue by suadhika** [vamsidarbhamulla/serenity-cucumber-bdd-screenplay#2]
Steps to reproduce:

1. Git cloned the project.
2. in serenity edited conf webdriver.chrome.driver = "/Users/susanta..../Downloads/chromedriver" ( running on MAC)
3. Ran the feature file sign_in_with_existing_account.feature

Expected Result: The Scenario should have run.

Actual Result: getting null pointer exception :

`ChromeDriver was started successfully.
May 04, 2021 5:31:04 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C

java.lang.NullPointerException
	at net.thucydides.core.steps.StepEventBus.updateOverallResults(StepEventBus.java:706)
	at net.serenitybdd.screenplay.EventBusInterface.updateOverallResult(EventBusInterface.java:34)
	at net.serenitybdd.screenplay.Actor.perform(Actor.java:157)
	at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:125)
	at net.serenitybdd.screenplay.Actor.wasAbleTo(Actor.java:119)
	at features.user_account.UserLoginStepDef.user_is_a_registered_member(UserLoginStepDef.java:32)
	at ✽.that Carla is a registered member(/Users/susanta.a.adhikary/Test/serenity-cucumber-bdd-screenplay/src/test/resources/features/user_account/sign_in_with_existing_account.feature:10)

Skipped step

Skipped step
[main] WARN cucumber.runtime.SerenityBackend - It looks like you are running a feature using @RunWith(Cucumber.class) instead of @RunWith(CucumberWithSerenity.class). Are you sure this is what you meant to do?

Failed scenarios:
/Users/susanta.a.adhikary/Test/serenity-cucumber-bdd-screenplay/src/test/resources/features/user_account/sign_in_with_existing_account.feature:9 # Sign in with valid user account

1 Scenarios (1 failed)
3 Steps (1 failed, 2 skipped)
0m3.609s

java.lang.NullPointerException
	at net.thucydides.core.steps.StepEventBus.updateOverallResults(StepEventBus.java:706)
	at net.serenitybdd.screenplay.EventBusInterface.updateOverallResult(EventBusInterface.java:34)
	at net.serenitybdd.screenplay.Actor.perform(Actor.java:157)
	at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:125)
	at net.serenitybdd.screenplay.Actor.wasAbleTo(Actor.java:119)
	at features.user_account.UserLoginStepDef.user_is_a_registered_member(UserLoginStepDef.java:32)
	at ✽.that Carla is a registered member(/Users/susanta.a.adhikary/Test/serenity-cucumber-bdd-screenplay/src/test/resources/features/user_account/sign_in_with_existing_account.feature:10)

`

The application page opens and closes immediately.

While debugging I found out : "java.lang.NullPointerException: No BaseStepListener has been registered"

**Comment by suadhika** [comment]
Did two things.
1. Updated the dependencies.
`    
ext{
    serenity_version = "2.4.4"
}

dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:2.4.4")
    }

dependencies {
    compile group: 'net.serenity-bdd', name: 'serenity-core', version:"$serenity_version"
    compile group: 'net.serenity-bdd', name: 'serenity-junit', version:"$serenity_version"
    compile group: 'net.serenity-bdd', name: 'serenity-cucumber6', version:"$serenity_version"
    compile group: 'net.serenity-bdd', name: 'serenity-screenplay', version:"$serenity_version"
    compile group: 'net.serenity-bdd', name: 'serenity-screenplay-rest', version:"$serenity_version"
    compile group: 'net.serenity-bdd', name: 'serenity-screenplay-webdriver', version:"$serenity_version"
    testCompile group: 'io.cucumber', name: 'cucumber-java', version:'6.10.0'
    testCompile group: 'io.cucumber', name: 'cucumber-junit', version:'6.10.0'
    testCompile group: 'junit', name: 'junit', version:'4.13'
    testCompile group: 'org.slf4j', name: 'slf4j-simple', version:'1.7.30'
}

`
2. Used the glue option to specify the stepDefinition files.
